version: "3.9"
services:
  realsense_ros2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.laptop_slam
    tty: true
    stdin_open: true
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /dev:/dev
      - ../config_rviz:/ros2_ws/config_rviz
      - ~/data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../terra_src:/ros2_ws/src
    command: bash
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
